# Generated by Django 4.2.6 on 2023-10-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='user_rating',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='User Rating'),
        ),
    ]
