# Generated by Django 4.2.6 on 2023-10-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userfavorite_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='user_rating',
            new_name='ratings',
        ),
    ]
