# Generated by Django 4.2.7 on 2023-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usersearchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersearchhistory',
            name='query',
        ),
        migrations.AddField(
            model_name='usersearchhistory',
            name='history',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='History'),
        ),
    ]
