# Generated by Django 4.2.6 on 2023-10-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terhal', '0003_alter_hotel_hotel_rating'),
        ('recommendation', '0002_remove_recommendation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='category',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='categories',
            field=models.ManyToManyField(to='terhal.category', verbose_name='Categories'),
        ),
    ]
