# Generated by Django 4.2.6 on 2023-10-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terhal', '0004_category_icon'),
        ('recommendation', '0005_rename_active_recommendationimage_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='recommendationimage',
            options={'verbose_name': 'Recommendation Image', 'verbose_name_plural': 'Recommendation Images'},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='hotels',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terhal.category', verbose_name='Categories'),
            preserve_default=False,
        ),
    ]
