# Generated by Django 4.2.6 on 2023-10-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terhal', '0005_delete_hotel_delete_hotelcategory'),
        ('recommendation', '0007_alter_recommendation_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terhal.category', verbose_name='Categorie'),
        ),
    ]
