# Generated by Django 4.2.6 on 2023-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(default='', max_length=255, verbose_name='Hashed Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='health_condition',
            field=models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Asthma', 'Asthma'), ('No Condition', 'No Condition')], max_length=255, null=True, verbose_name='Health Condition'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='need_stroller',
            field=models.BooleanField(default=False, verbose_name='Need Stroller'),
        ),
        migrations.AddField(
            model_name='user',
            name='travel_companion',
            field=models.CharField(blank=True, choices=[('Family', 'Family'), ('Solo', 'Solo')], max_length=6, null=True, verbose_name='Travel Companion'),
        ),
    ]
