# Generated by Django 4.2.6 on 2023-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_name_user_date_of_birth_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UID'),
        ),
    ]
