# Generated by Django 4.2.6 on 2023-10-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userrating_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='favorites',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Favorites'),
        ),
    ]
