# Generated by Django 4.2.7 on 2023-11-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_user_rating_userrating_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hashed_password',
        ),
    ]
