# Generated by Django 4.2.6 on 2023-10-13 05:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('terhal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Hotel Category',
                'verbose_name_plural': 'Hotel Categories',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('hotel_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Hotel Rating')),
                ('rooms', models.JSONField(default=dict, verbose_name='Rooms')),
                ('categories', models.ManyToManyField(to='terhal.hotelcategory', verbose_name='Categories')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
