# Generated by Django 4.2.6 on 2023-10-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_alter_recommendation_options_and_more'),
        ('terhal', '0004_category_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelCategory',
        ),
    ]
