# Generated by Django 4.2.6 on 2023-10-31 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='csv_file',
            field=models.FileField(upload_to='recommendation/data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
