# Generated by Django 4.2.6 on 2023-10-13 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terhal', '0002_hotelcategory_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Hotel Rating'),
        ),
    ]
