# Generated by Django 4.2.6 on 2023-10-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terhal', '0003_alter_hotel_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='0xe322', max_length=9, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
