# Generated by Django 4.2.6 on 2023-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terhal', '0005_delete_hotel_delete_hotelcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(upload_to='category_icons/', verbose_name='Icon'),
        ),
    ]
